[package]
name = "spin-sqlite-libsql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
# We don't actually use rusqlite itself, but we'd like the same bundled
# libsqlite3-sys as used by spin-sqlite-inproc.
libsql = { version = "0.3.2", features = ["remote"], default-features = false }
rusqlite = { version = "0.29.0", features = ["bundled"] }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-world = { path = "../world" }
sqlparser = "0.34"
tokio = { version = "1", features = ["full"] }
tracing = { workspace = true }

[lints]
workspace = true
