[package]
name = "spin-serde"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
base64 = "0.22.1"
semver = { version = "1.0", features = ["serde"] }
serde = "1.0.189"
wasm-pkg-common = "0.4.1"
