[package]
name = "spin-sqlite"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-factors = { path = "../factors" }
spin-locked-app = { path = "../locked-app" }
spin-resource-table = { path = "../table" }
spin-sqlite-inproc = { path = "../sqlite-inproc" }
spin-sqlite-libsql = { path = "../sqlite-libsql" }
spin-world = { path = "../world" }
tokio = { workspace = true }
toml = { workspace = true }
