[package]
name = "spin-factor-wasi"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
cap-primitives = "3.0.0"
spin-common = { path = "../common" }
spin-factors = { path = "../factors" }
tokio = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }

[dev-dependencies]
spin-factors-test = { path = "../factors-test" }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
