[package]
name = "spin-key-value-spin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
once_cell = "1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0", features = ["rc"] }
spin-core = { path = "../core" }
spin-factor-key-value = { path = "../factor-key-value" }
spin-world = { path = "../world" }
tokio = { version = "1", features = ["rt-multi-thread"] }

[lints]
workspace = true
