[package]
name = "spin-componentize"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
wasmparser = "0.200.0"
wasm-encoder = "0.200.0"
wit-component = "0.200.0"
wit-parser = "0.200.0"

[dev-dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
tokio = { version = "1.36.0", features = ["macros", "rt", "fs"] }
# spin-abi-conformance = { path = "abi-conformance" }
