[package]
name = "spin-key-value-redis"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
redis = { version = "0.21", features = ["tokio-comp", "tokio-native-tls-comp"] }
serde = { version = "1.0", features = ["rc"] }
spin-core = { path = "../core" }
spin-factor-key-value = { path = "../factor-key-value" }
spin-world = { path = "../world" }
tokio = "1"
tracing = { workspace = true }
url = "2"

[lints]
workspace = true
