[package]
name = "outbound-http"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
http = "0.2"
reqwest = { version = "0.11", features = ["gzip"] }
spin-app = { path = "../app", optional = true }
spin-core = { path = "../core", optional = true }
spin-expressions = { path = "../expressions", optional = true }
spin-locked-app = { path = "../locked-app" }
spin-outbound-networking = { path = "../outbound-networking" }
spin-world = { path = "../world", optional = true }
terminal = { path = "../terminal" }
tracing = { workspace = true }
url = "2.2.1"

[features]
default = ["runtime"]
runtime = ["dep:spin-app", "dep:spin-core", "dep:spin-expressions", "dep:spin-world"]
