[package]
name = "spin-factor-key-value"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["rc"] }
spin-factors = { path = "../factors" }
# TODO: merge with this crate
spin-key-value = { path = "../key-value" }
spin-world = { path = "../world" }
toml = "0.8"

[dev-dependencies]
spin-factor-key-value-redis = { path = "../factor-key-value-redis" }
spin-factor-key-value-spin = { path = "../factor-key-value-spin" }
spin-factors-test = { path = "../factors-test" }
tempfile = "3.12.0"
tokio = { version = "1", features = ["macros", "rt"] }


[lints]
workspace = true
