[package]
name = "spin-key-value-sqlite"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
once_cell = "1"
rusqlite = { version = "0.29.0", features = [ "bundled" ] }
tokio = "1"
spin-key-value = { path = "../key-value" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
tracing = { workspace = true }

[lints]
workspace = true
