[package]
name = "spin-key-value-azure"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
azure_data_cosmos = { git = "https://github.com/azure/azure-sdk-for-rust.git", rev = "8c4caa251c3903d5eae848b41bb1d02a4d65231c" }
azure_identity = { git = "https://github.com/azure/azure-sdk-for-rust.git", rev = "8c4caa251c3903d5eae848b41bb1d02a4d65231c" }
futures = "0.3.28"
serde = { version = "1.0", features = ["derive"] }
spin-key-value = { path = "../key-value" }
spin-core = { path = "../core" }
tokio = "1"
url = "2"
tracing = { workspace = true }

[lints]
workspace = true
