[package]
name = "spin-sqlite-inproc"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
once_cell = "1"
rand = "0.8"
rusqlite = { version = "0.29.0", features = ["bundled"] }
spin-sqlite = { path = "../sqlite" }
spin-world = { path = "../world" }
tokio = "1"
tracing = { workspace = true }

[lints]
workspace = true
