[package]
name = "outbound-mqtt"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
paho-mqtt = { version = "0.12.3", default-features = false, features = ["vendored-ssl"] }
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
spin-outbound-networking = { path = "../outbound-networking" }
table = { path = "../table" }
tokio = { version = "1", features = ["sync"] }
tracing = { workspace = true }
