name: Dispatch Event

on:
  push:
    branches: [main, "v*"]
    tags: ["v*"]

jobs:
  dispatch-rust-docs:
    name: Dispatch rust-docs spin-update event
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'spinframework' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          repository: spinframework/rust-docs
          event-type: spin-update
          client-payload: '{"ref": "${{ github.ref_name }}"}'