[package]
name = "test-codegen-macro"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
heck = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
