[package]
name = "test-codegen-macro"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
heck = "0.4.0"
quote = "1.0.32"
syn = "2.0"
